# Copyright (c) Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
# cmake/embed_corpus.cmake
#
# fastrpc_embed_corpus(<entry_point> <corpus_dir> <out_var>) generates a C
# source file that embeds every seed file directly under <corpus_dir> as a
# `static const unsigned char[]`, plus a `struct fuzz_embedded_corpus
# fuzz_embedded_corpus_<entry_point>` (see fuzz_embedded_corpus.h) listing
# them. <out_var> is set to the generated file's path, which the caller adds
# to its suite's sources.
#
# Pure-CMake byte embedding (file(READ ... HEX) + a regex pass to turn hex
# pairs into "0x.., " tokens) — no xxd/python/objcopy dependency, but doesn't
# scale past the tiny hand-picked seed corpora this project checks in; if a
# corpus dir ever needs real bulk (hundreds of KB+) seeds, use a real corpus
# directory on disk instead of growing this further.
function(fastrpc_embed_corpus entry_point corpus_dir out_var)
    file(GLOB _seed_files LIST_DIRECTORIES false "${corpus_dir}/*")

    set(_decls "")
    set(_entries "")
    set(_index 0)

    foreach(_seed_file IN LISTS _seed_files)
        get_filename_component(_seed_name "${_seed_file}" NAME)

        file(READ "${_seed_file}" _hex HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _hex_bytes "${_hex}")

        set(_array_name "${entry_point}_seed_${_index}")
        string(APPEND _decls
            "static const unsigned char ${_array_name}[] = { ${_hex_bytes} };\n")
        string(APPEND _entries
            "    { \"${_seed_name}\", ${_array_name}, sizeof(${_array_name}) },\n")

        math(EXPR _index "${_index} + 1")
    endforeach()

    set(_out_file "${CMAKE_CURRENT_BINARY_DIR}/generated/fuzz_embedded_corpus_${entry_point}.c")

    file(WRITE "${_out_file}"
"// Generated by cmake/embed_corpus.cmake from ${corpus_dir} — do not hand-edit.
#include \"fuzz_embedded_corpus.h\"

${_decls}
static const struct fuzz_embedded_seed ${entry_point}_seeds[] = {
${_entries}};

const struct fuzz_embedded_corpus fuzz_embedded_corpus_${entry_point} = {
    \"${entry_point}\",
    ${entry_point}_seeds,
    ${_index},
};
")

    set(${out_var} "${_out_file}" PARENT_SCOPE)
endfunction()
